package com.hibernate.mantenimiento.entidad;
// Generated 29-ene-2020 15:54:29 by Hibernate Tools 5.4.7.Final

/**
 * Alumno generated by hbm2java
 */
public class Alumno implements java.io.Serializable {

	private String nif;
	private String nombre;
	private String apellidos;
	private Character sexo;
	private Integer nota1;
	private Integer nota2;

	public Alumno() {
	}

	public Alumno(String nif) {
		this.nif = nif;
	}

	public Alumno(String nif, String nombre, String apellidos, Character sexo, Integer nota1, Integer nota2) {
		this.nif = nif;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.sexo = sexo;
		this.nota1 = nota1;
		this.nota2 = nota2;
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Character getSexo() {
		return this.sexo;
	}

	public void setSexo(Character sexo) {
		this.sexo = sexo;
	}

	public Integer getNota1() {
		return this.nota1;
	}

	public void setNota1(Integer nota1) {
		this.nota1 = nota1;
	}

	public Integer getNota2() {
		return this.nota2;
	}

	public void setNota2(Integer nota2) {
		this.nota2 = nota2;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("nif").append("='").append(getNif()).append("' ");
		buffer.append("nombre").append("='").append(getNombre()).append("' ");
		buffer.append("apellidos").append("='").append(getApellidos()).append("' ");
		buffer.append("sexo").append("='").append(getSexo()).append("' ");
		buffer.append("nota1").append("='").append(getNota1()).append("' ");
		buffer.append("nota2").append("='").append(getNota2()).append("' ");
		buffer.append(calculaApto()); // <--- Añadido Manualmente
		buffer.append("]");

		return buffer.toString();
	}

	// The following is extra code specified in the hbm.xml files

	private String calculaApto() {
		if (nota1 >= 5) {
			if (nota2 >= 5) {
				return "Alumno Apto";
			} else {
				return "Alumno NO Apto";
			}
		} else {
			return "Alumno NO Apto";
		}
	}

	// end of extra code specified in the hbm.xml files

}
